name: Sync from upstream
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - run: |
          git remote add upstream https://github.com/asteroidimpact/asteroid_impact_py3.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories -m "Sync from upstream"
          git push origin master
